### ISSUE TITLE
i/o levels

### ISSUE THREAD

**Issue by ShofB** [eh2k/fv1-emu#2]
First of all what a great idea.  In general I have found the input has to be pushed harder than other Rack plugins.  Also for the most part the output is much lower than other plugins.  I have to turn a mixer channel up to max and even then the meter is barely bumping  This is not for all patches but for a lot of them.  Having knobs for each of these with an amplified output would be nice.

**Comment by eh2k** [comment]
@ShofB, thank you for your feedback.

As I understand, your output signal is lower than excepted (on some dsp-programs), and you are missing an additional output amplification ?

At the moment the ``` output = input + fv1-output```, when the dry/wet knob is at center. 

If the fv1-output is the input signal, the mixed output is amplifyed by factor 2.

Usually the output shoud never been lower than the input, except the signal is completly wet (depending on dsp-programm, there the amplification can be implemented also).

I'll consider about it, but I don't want to overcomplicate the module..
