### ISSUE TITLE
A newer version ?

### ISSUE THREAD

**Issue by nicotep** [eh2k/fv1-emu#3]
Sorry, that's not properly an "issue"... Just to ask if you plan to update the FV-1 emulator for VCV. 
I did update VCV and it's impossible to downgrade. Your module was very useful for testing purpose.
Thanks anyway

**Comment by eh2k** [comment]
Sorry, no time for upgrading to current VCV version... Pull requestes welcome.

**Comment by netboy3** [comment]
I've ported the plugin to V1 and posted [pull request for the OP](https://github.com/eh2k/fv1-emu/pull/5). I've built test releases that you can use on [my fork release page](https://github.com/netboy3/fv1emu-vcvrack-plugins/releases/tag/1.0.0).

**Comment by eh2k** [comment]
@netboy3, thank you for upgrading to V1.
 I think the plugin will be available in the VCVRack library next days. (VCVRack/library#636).
