### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by djdoz** [eh2k/fv1-emu#4]
Not really a bug, however, I'm attempting to install this on a Windows laptop. I"ve downloaded the fv1-emu-master.zip onto Documents/Rack/plugins_v1 folder. When I start VCVRack, I can  see it uncompress the zip file however, I'm unable to see it as a plugin in VCV Rack. Looks like it is missing some files?

**Comment by eh2k** [comment]
Plugin is working only with VCV version 0.6.  It is not yet ported vor v1 version #3.

**Comment by djdoz** [comment]
Just wanted to ask, how do I compile and install on version 0.6?

Apologies for the newb questions.

**Comment by eh2k** [comment]
Here you can find all the information you need to compile rack itself, or any plugin.

https://vcvrack.com/manual/Building

**Comment by djdoz** [comment]
Ok, I download VCV Rack 0.6.1 and VCV Rack sdk 0.6.1 and compiled it using the commands make and make dist. This gives me a zip file where I loaded into the plugin folder. When I start VCV Rack it extracts the zip file but I get the below error message.
[0.230 warn src/plugin.cpp:84] Failed to load library C:\Users\djd_o\OneDrive\Documents/Rack/plugins/EH_modules/plugin.dll: code 127
Any idea why this is happening?

    On Sunday, 15 March 2020, 02:34:43 am AEDT, Eduard Heidt <notifications@github.com> wrote:  
 
 


Here you can find all the information you need to compile rack itself, or any plugin.

https://vcvrack.com/manual/Building

**Comment by eh2k** [comment]
was the plugin.dll also compiled or downloaden somewhere?
Pleased verify Rack.exe and plugin.dll are both same architecture (x86 or x64).

**Comment by djdoz** [comment]
Thank you for your support on this.
I downloaded the below files from https://vcvrack.com/downloads/Rack-0.6.1-win.exe andRack-SDK-0.6.1.zipAnd then I complied it using the below commands,
make
make dist
After that I copied the EH_modules-0.6.1-win.zip into the Rack/plugin Folder
Can confirm the below,
djd_o@DESKTOP-3PBVRH5 MINGW64 /c/Users/djd_o/OneDrive/Documents/Rack/plugins/EH_modules$ file /c/Program\ Files/VCV_06/Rack/Rack.exe/c/Program Files/VCV_06/Rack/Rack.exe: PE32+ executable (GUI) x86-64 (stripped to external PDB), for MS Windows
djd_o@DESKTOP-3PBVRH5 MINGW64 /c/Users/djd_o/OneDrive/Documents/Rack/plugins/EH_modules$ file plugin.dllplugin.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows



    On Thursday, 19 March 2020, 03:49:05 am AEDT, Eduard Heidt <notifications@github.com> wrote:  
 
 


was the plugin.dll also compiled or downloaden somewhere?
Pleased verify Rack.exe and plugin.dll are both same architecture (x86 or x64).

**Comment by eh2k** [comment]
I would clone the repo into the Rack/plugins directory. You can compile the plugin.dll with a simple "make" also. 
Maybe the downloaded dll is not compatible with your version of MinGW or any dependency.

**Comment by netboy3** [comment]
I've ported the plugin to V1 and posted [pull request for the OP](https://github.com/eh2k/fv1-emu/pull/5). I've built test releases that you can use on [my fork release page](https://github.com/netboy3/fv1emu-vcvrack-plugins/releases/tag/1.0.0).

**Comment by eh2k** [comment]
@netboy3, thank you for upgrading to V1. 
@djdoz, I think the plugin will be available in de VCVRack library in the next days. (https://github.com/VCVRack/library/issues/636).
