### ISSUE TITLE
Loading third-party .spn file crashes Rack application

### ISSUE THREAD

**Issue by inscripttech** [eh2k/fv1-emu#6]
Love the module idea. This is my first git issue so I'm open to feedback/critique if I have opened the issue incorrectly.

Loading the SpinASM file at this location:
https://mstratman.github.io/fv1-programs/files/dervish/drv102/dv102-1head-reverb.spn

Results in crashing VCV Rack with the dialogue:
VCV Rack has crashed. See [path] for details.

My log after engine startup shows:
`[1.205 info src/main.cpp:189] Starting engine
[1.205 info src/main.cpp:201] Running window
[68.355 fatal src/main.cpp:45] Fatal signal 22. Stack trace:
23: ZN4rack10appDestroyEv 0x456435
22: raise 0x2781ac60
21: abort 0x2781f270
20: assert 0x2781b510
19: ZN6FV1emu8ParseIntERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt3mapIS5_iSt4lessIS5_ESaISt4pairIS6_iEEE 0x77e83f0
18: ZN6FV1emu4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x77e2300
17: ZN12FV1EmuModule6loadFxERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x77daa90
16: ZN12PathMenuItem8onActionERKN4rack5event6ActionE 0x77ddb40
15: ZN4rack2ui8MenuItem8doActionEv 0x4a49ae
14: ZN4rack5event5State12handleButtonENS_4math3VecEiii 0x4576c8
13: ZN4rack7updater17isUpdateAvailableEv 0x45914e
12: glfwPlatformUnlockMutex 0x4d78ae
11: CallWindowProcW 0x272b5850
10: CallWindowProcW 0x272b5850
9: glPushClientAttrib 0xebdb3770
8: CallWindowProcW 0x272b5850
7: DispatchMessageW 0x272b5410
6: glfwPlatformPollEvents 0x4daf66
5: ZN4rack6Window3runEv 0x4594ea
4: main 0x781840
3: main 0x781840
2: main 0x781840
1: BaseThreadInitThunk 0x28077bc0
0: RtlUserThreadStart 0x28f0ceb0`

**Comment by eh2k** [comment]
HI, thank you for crash reporting.
The crash will be fixed in the next 1.0.1 update.

I didn't know https://mstratman.github.io/fv1-programs/  before.
Unfortunately a lot of the effects are not sounding well.
Maybe where are some issues in the spn parsing or as I remember the CHO_RDA/CHO_SOF implementation  was not straightforward.
