### ISSUE TITLE
RDA is wrong interperated

### ISSUE THREAD

**Issue by rizacab2001** [eh2k/fv1-emu#9]
There is no phase between  LFO1 SIN and LFO1 COS signals. It is the same for LFO2

If we use RDA 4 iinstead of RDA 8,( LFO1) and  use RDA 5  instead of RDA9
For LFO2 then , it works fine

**Comment by eh2k** [comment]
Thank you for your feedback.
Could you please provide some example code, so I can reproduce the issue.
If possible you can try to give me a hint/suggestion on the code directly. Please see: 

https://github.com/eh2k/fv1-emu/blob/master/src/FV1.hpp#L573-L615

I've checked the lfo sin/cos phase with CHO RDAL and it is ok so far:

````
skp run,START

wlds SIN0,125,0

START: 

ldax POT0
wrax SIN0_RANGE,0

rdax POT1,0.7338
sof 1.0,0.2446
wrax SIN0_RATE,0

cho rdal,COS0
wrax DACL,0

cho rdal,SIN0
wrax DACR,0
```` 

![image](https://user-images.githubusercontent.com/11786292/83728354-9a9b1e00-a646-11ea-99ed-bc2282158e40.png)

**Comment by rizacab2001** [comment]
; Untitled
; null
; Pot 0: 
; Pot 1: 
; Pot 2: 
; 
; 
; ----------------------------
;------ Pot 0
;------ Pot 1
;------ LFO 0
SKP RUN ,1
WLDS 0,511,16387
RDAX POT0,1.0000000000
WRAX SIN0_RATE,0.0000000000
RDAX POT1,0.5001068148
WRAX SIN0_RANGE,0.0000000000
CHO RDAL,0
WRAX REG0,0.0000000000
CHO RDAL,8
WRAX REG1,0.0000000000
;------ Output
RDAX REG1,1.0000000000
WRAX DACL,0.0000000000
RDAX REG0,1.0000000000
WRAX DACR,0.0000000000

This a simple program made by Spincad builder.
CHO RDAL,8, is not correct.. If we use  CHO RDAL,4   it works fine. May be this is a Spincad buiider Bug

**Comment by rizacab2001** [comment]
Similar situation happens for LFO1,But CHO RDAL,9  must be CHO RDAL,5

**Comment by eh2k** [comment]
I've found a similar thread in the spinsemi forum: http://www.spinsemi.com/forum/viewtopic.php?p=2128

I think the assembler error message ist the answer:

````
<0000>[ Pass 2] [ 1021] Line: 8 "CHO RDAL,4 " - ERROR:Integer Value out of Range - CHO RDAL[LFO] should be 'SIN0 (0)','SIN1 (1)','COS0 (8)','COS1 (9)','RMP0 (2) ' or 'RMP1 (3)'
<0001>[ Pass 2] [ 1021] Line: 16 "CHO RDAL,5 " - ERROR:Integer Value out of Range - CHO RDAL[LFO] should be 'SIN0 (0)','SIN1 (1)','COS0 (8)','COS1 (9)','RMP0 (2) ' or 'RMP1 (3)'
````
The defines for cos0/cos1 have to be changed from 4/5 to 8/9.

**Comment by rizacab2001** [comment]
Thanks for the great fv1 emu module. Now I can make solina ensembe  
effect more confortable :)

  Alıntı Eduard Heidt <notifications@github.com>:

>  
>
>   I've found a similar thread in the spinsemi forum:  
> http://www.spinsemi.com/forum/viewtopic.php?p=2128
>
>   I think the assembler error message ist the answer:
> <0000>[ Pass 2] [ 1021] Line: 8 "CHO RDAL,4 " - ERROR:Integer Value  
> out of Range - CHO RDAL[LFO] should be 'SIN0 (0)','SIN1 (1)','COS0  
> (8)','COS1 (9)','RMP0 (2) ' or 'RMP1 (3)' <0001>[ Pass 2] [ 1021]  
> Line: 16 "CHO RDAL,5 " - ERROR:Integer Value out of Range - CHO  
> RDAL[LFO] should be 'SIN0 (0)','SIN1 (1)','COS0 (8)','COS1  
> (9)','RMP0 (2) ' or 'RMP1 (3)'
>   The defines for cos0/cos1 have to be changed from 4/5 to 8/9.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].



Bağlantılar:
------------
[1] https://github.com/eh2k/fv1-emu/issues/9#issuecomment-638821564
[2]
